version: '3'
networks:
 favourite_currency_project_network:
   
services:
  swerwis_nginx_z_php:
   image: webdevops/php-nginx:8.0
   container_name: nginx_favourite_currency
   depends_on:
   - postgres
   ports:
   - "${NGINX_PORT}:80"
   volumes:
   - ./laravel_project:/app
   - ./vhost_config/vhost.conf:/opt/docker/etc/nginx/vhost.conf
   networks:
    - favourite_currency_project_network

  postgres:
   image: postgres:14
   container_name: postgres_favourite_currency
   restart: always
   tty: true
   ports:
   - "${OUTSIDE_DB_PORT}:5432"
   volumes:
   - ./postgres_data:/var/lib/postgresql/data
   environment:
    - "POSTGRES_PASSWORD=${DB_PASSWORD}"   
    - PGDATA="/var/lib/postgresql/data/pgdata"
   networks:
    - favourite_currency_project_network

  postgres_for_testing:
   image: postgres:14
   container_name: postgres_for_testing_favourite_currency
   restart: always
   tty: true
   ports:
   - "${OUTSIDE_DB_PORT_FOR_TESTING}:5432"
   volumes:
   - ./postgres_for_testing_data:/var/lib/postgresql/data
   environment:
    - "POSTGRES_PASSWORD=${DB_PASSWORD_DB_FOR_TESTING}"   
    - PGDATA="/var/lib/postgresql/data/pgdata"
   networks:
    - favourite_currency_project_network  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_favourite_currency
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}"
    restart: always
    networks:
    - favourite_currency_project_network

volumes:
  postgres_data:
    driver: local